import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { sanitizeFileName } from "./csv";

export function exportSurveyRawPDF({ rows, title }) {
  const data = rows;
  if (!Array.isArray(data) || data.length === 0) {
    throw new Error("No data to export");
  }

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Modern gradient header background
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  // Accent bar
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Title section
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(undefined, 'bold');
  doc.text("Survey Data Report", 14, 15);
  
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Survey: ${title}`, 14, 22);
  
  doc.setFontSize(9);
  const exportDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.text(`Exported: ${exportDate}`, 14, 28);
  
  // Total responses badge
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(pageWidth - 70, 12, 56, 12, 3, 3, 'F');
  doc.setTextColor(59, 130, 246);
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text(`Total: ${data.length} responses`, pageWidth - 42, 19, { align: 'center' });

  // Reset text color for table
  doc.setTextColor(0, 0, 0);

  // Prepare table data with English headers
  const tableData = data.map((row) => [
    row["ID Phản hồi"] || row["Response ID"] || "",
    row["Mã SV"] || row["Student ID"] || "",
    row["Tên Sinh viên"] || row["Student Name"] || "",
    row["Khoa"] || row["Faculty"] || "",
    row["Ngày Hoàn thành"] || row["Completed Date"] || "",
  ]);

  autoTable(doc, {
    startY: 40,
    head: [["Response ID", "Student ID", "Student Name", "Faculty", "Completed Date"]],
    body: tableData,
    theme: "grid",
    headStyles: { 
      fillColor: [59, 130, 246],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 10,
      halign: 'center',
      cellPadding: 4
    },
    styles: { 
      fontSize: 9,
      cellPadding: 3,
      lineColor: [226, 232, 240],
      lineWidth: 0.1
    },
    columnStyles: { 
      0: { cellWidth: 30, halign: 'center' },
      1: { cellWidth: 35, halign: 'center' },
      2: { cellWidth: 70 },
      3: { cellWidth: 45 },
      4: { cellWidth: 45, halign: 'center' }
    },
    alternateRowStyles: { 
      fillColor: [248, 250, 252]
    },
    margin: { top: 40, left: 14, right: 14, bottom: 25 },
    didDrawPage: (dataHook) => {
      const pageCount = doc.internal.getNumberOfPages();
      
      // Footer background
      doc.setFillColor(249, 250, 251);
      doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');
      
      // Footer line
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);
      
      // Page number
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.setFont(undefined, 'normal');
      doc.text(
        `Page ${dataHook.pageNumber} of ${pageCount}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
      
      // Branding
      doc.setFontSize(8);
      doc.text(
        "Generated by Survey System",
        pageWidth - 14,
        pageHeight - 8,
        { align: 'right' }
      );
    },
  });

  const fileName = `${sanitizeFileName(title)}_${Date.now()}.pdf`;
  doc.save(fileName);
}
