# --- Base image ---
FROM php:8.3-fpm

# --- Install system dependencies ---
RUN apt-get update && apt-get install -y \
    git curl zip unzip libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev libzip-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# --- Install Composer ---
COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

# --- Set working directory ---
WORKDIR /var/www

# --- Copy only composer files to install dependencies ---
COPY composer.json composer.lock ./
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install --no-scripts --no-autoloader

# --- Copy source code ---
COPY . .

# --- Install Xdebug ---
RUN pecl install xdebug-3.3.1 \
    && docker-php-ext-enable xdebug

# --- Add Xdebug config ---
COPY ./docker/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# --- Give write permission for Laravel ---
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
